title: Kiran Mohite
description: ETL Engineer | Python | SQL | Data Pipelines | Automation | Snowflake
theme: minima

author:
  name: Kiran Mohite
  email: kiranmohite@email.com

social_links:
  github: https://github.com/kiranmohite6004
  linkedin: https://www.linkedin.com/in/kiranmohite6004/
